### ISSUE TITLE
Setting particle positions

### ISSUE THREAD

**Issue by zcanter** [IdeaSpaceVR/aframe-particle-system-component#18]
Is there a way to override particle positions? Let's say I had a JSON file with a collection of x,y,z positions and I wanted to put particles in those spots. Thank you!

**Comment by chriscar** [comment]
You could put the a-frame entities / particle emitters in these spots. Please have a look at the a-frame docs in order to find out how to position a-frame entities. This component is just a thin wrapper around https://github.com/squarefeet/ShaderParticleEngine . And I doubt you can control the positions of single particles, buy maybe I am wrong. Why not position simple a-frame entities in your desired positions?

**Comment by chriscar** [comment]
I see! Just in case you did not see the API doc of the particle engine I am using: https://squarefeet.github.io/ShaderParticleEngine/docs/api/SPE.Group.html . I have no experience with https://github.com/pwambach/threejs-particle-shader though. Anyways, good luck with your project!
